const products=[
{id:1,name:"Smartphone Galaxy A55 5G 128GB",category:"celulares",price:1899.9,old:2199.9,discount:14,img:"https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=700&q=80"},
{id:2,name:"iPhone 13 128GB",category:"celulares",price:2799.9,old:3199.9,discount:13,img:"https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=700&q=80"},
{id:3,name:"Smart TV 50 4K UHD",category:"tv",price:2199.9,old:2599.9,discount:15,img:"https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=700&q=80"},
{id:4,name:"Notebook 15,6 Core i5 8GB 512GB",category:"informatica",price:3299.9,old:3899.9,discount:15,img:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=700&q=80"},
{id:5,name:"PlayStation 5 Slim",category:"games",price:3599.9,old:3999.9,discount:10,img:"https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=700&q=80"},
{id:6,name:"Air Fryer 5,5L Digital",category:"eletro",price:399.9,old:549.9,discount:27,img:"https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=700&q=80"},
{id:7,name:"Headset Gamer Sem Fio",category:"games",price:249.9,old:329.9,discount:24,img:"https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=700&q=80"},
{id:8,name:"Monitor Gamer 27 165Hz",category:"informatica",price:1099.9,old:1399.9,discount:21,img:"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=700&q=80"}];
let state={category:"all",search:"",cart:JSON.parse(localStorage.getItem("ur-cart")||"[]")};
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function filtered(){let x=products.filter(p=>(state.category==="all"||p.category===state.category)&&p.name.toLowerCase().includes(state.search.toLowerCase()));const s=document.getElementById("sort").value;if(s==="low")x.sort((a,b)=>a.price-b.price);if(s==="high")x.sort((a,b)=>b.price-a.price);return x}
function renderProducts(){const g=document.getElementById("productGrid"),x=filtered();g.innerHTML=x.length?x.map(p=>'<article class="product" onclick="openProduct('+p.id+')"><span class="tag">'+p.discount+'% OFF</span><img src="'+p.img+'" alt="'+p.name+'" loading="lazy"><div class="stars">★★★★★ <small>(4.8)</small></div><h3>'+p.name+'</h3><div class="old">'+money(p.old)+'</div><div class="price">'+money(p.price)+'</div><div class="pix">à vista no Pix</div><button class="buy" onclick="event.stopPropagation();addCart('+p.id+')">Adicionar ao carrinho</button></article>').join(""):'<div class="empty">Nenhum produto encontrado.<br><button onclick="clearSearch()">Limpar filtros</button></div>'}
function filterCategory(c){state.category=c;state.search="";document.getElementById("searchInput").value="";const names={celulares:"Celulares",tv:"TV e Vídeo",informatica:"Informática",eletro:"Casa",games:"Games"};document.getElementById("sectionTitle").textContent=c==="all"?"Em destaque":names[c];document.querySelectorAll(".category-nav button,.chip").forEach(b=>b.classList.remove("active"));renderProducts();document.getElementById("produtos").scrollIntoView({behavior:"smooth"});toggleMenu(false)}
function filterSale(){state.category="all";state.search="";document.getElementById("sectionTitle").textContent="Ofertas";renderProducts();document.getElementById("produtos").scrollIntoView({behavior:"smooth"});toggleMenu(false)}
function searchProducts(){state.search=document.getElementById("searchInput").value.trim();state.category="all";document.getElementById("sectionTitle").textContent=state.search?'Resultados para "'+state.search+'"':"Em destaque";renderProducts();document.getElementById("produtos").scrollIntoView({behavior:"smooth"})}
function focusSearch(){document.querySelector(".desktop-search").scrollIntoView({behavior:"smooth"});setTimeout(()=>document.getElementById("searchInput").focus(),250)}
document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")searchProducts()});
function addCart(id){const item=state.cart.find(x=>x.id===id);if(item)item.qty++;else state.cart.push({id:id,qty:1});saveCart();showToast("Produto adicionado ao carrinho")}
function saveCart(){localStorage.setItem("ur-cart",JSON.stringify(state.cart));renderCart()}
function renderCart(){const el=document.getElementById("cartItems"),count=state.cart.reduce((n,x)=>n+x.qty,0),total=state.cart.reduce((n,x)=>n+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);document.getElementById("cartCount").textContent=count;document.getElementById("cartTotal").textContent=money(total);el.innerHTML=state.cart.length?state.cart.map(x=>{const p=products.find(p=>p.id===x.id);return '<div class="cart-row"><img src="'+p.img+'"><div><h4>'+p.name+'</h4><div>'+money(p.price)+'</div><div class="qty">Qtd: '+x.qty+' · <button onclick="removeCart('+p.id+')">remover</button></div></div><b>'+money(p.price*x.qty)+'</b></div>'}).join(""):'<div class="empty">Seu carrinho está vazio.</div>'}
function removeCart(id){state.cart=state.cart.filter(x=>x.id!==id);saveCart()}
function toggleCart(){document.getElementById("cart").classList.toggle("open");document.getElementById("overlay").classList.toggle("open")}
function toggleMenu(force){const n=document.getElementById("categoryNav");if(force===false)n.classList.remove("menu-open");else n.classList.toggle("menu-open")}
function openProduct(id){const p=products.find(x=>x.id===id);document.getElementById("modalContent").innerHTML='<div class="modal-product"><img src="'+p.img+'" alt="'+p.name+'"><div><div class="eyebrow">UR KINGSLAY</div><h2>'+p.name+'</h2><div class="stars">★★★★★ 4.8</div><div class="old">'+money(p.old)+'</div><div class="price">'+money(p.price)+'</div><p class="pix">à vista no Pix</p><p>Produto em destaque com envio para todo o Brasil.</p><button class="buy" onclick="addCart('+p.id+');closeModal()">Adicionar ao carrinho</button></div></div>';document.getElementById("modal").classList.add("open")}
function closeModal(e){if(!e||e.target.id==="modal")document.getElementById("modal").classList.remove("open")}
function checkout(){if(!state.cart.length)return showToast("Seu carrinho está vazio");showToast("Checkout será conectado na próxima etapa")}
function showAccount(){showToast("Área de conta será conectada na próxima etapa")}
function subscribe(e){e.preventDefault();showToast("Cadastro realizado!");e.target.reset()}
function showToast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function clearSearch(){state.search="";state.category="all";document.getElementById("searchInput").value="";document.getElementById("sectionTitle").textContent="Em destaque";renderProducts()}
function goHome(){state.category="all";state.search="";document.getElementById("sectionTitle").textContent="Em destaque";document.getElementById("searchInput").value="";window.scrollTo({top:0,behavior:"smooth"});renderProducts()}
renderProducts();renderCart();