const products=[
{id:1,name:"Blusa UrKingslay Basic",category:"moda",price:129.9,old:159.9,discount:19,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=85"},
{id:2,name:"Shorts Preto Casual",category:"moda",price:89.9,old:119.9,discount:25,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=700&q=85"},
{id:3,name:"Calça Bege Wide Leg",category:"moda",price:119.9,old:159.9,discount:25,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&w=700&q=85"},
{id:4,name:"Tênis Branco Casual",category:"moda",price:159.9,old:199.9,discount:20,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85"},
{id:5,name:"Saia Estampada Floral",category:"moda",price:99.9,old:139.9,discount:29,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1583496661160-fb5886a13d27?auto=format&fit=crop&w=700&q=85"},
{id:6,name:"Bolsa Preta Matelassê",category:"moda",price:139.9,old:179.9,discount:22,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=700&q=85"},
{id:7,name:"Camisa Branca Oversized",category:"moda",price:109.9,old:149.9,discount:27,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=700&q=85"},
{id:8,name:"Jaqueta Jeans Clara",category:"moda",price:179.9,old:229.9,discount:22,buyUrl:"",isFashion:true,img:"https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=700&q=85"}];
let state={category:"all",search:"",cart:JSON.parse(localStorage.getItem("ur-cart")||"[]"),favorites:JSON.parse(localStorage.getItem("ur-favorites")||"[]")};
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function filtered(){let x=products.filter(p=>(state.category==="all"||p.category===state.category)&&p.name.toLowerCase().includes(state.search.toLowerCase()));const s=document.getElementById("sort").value;if(s==="low")x.sort((a,b)=>a.price-b.price);if(s==="high")x.sort((a,b)=>b.price-a.price);return x}
function renderProducts(){const g=document.getElementById("productGrid"),x=filtered();g.innerHTML=x.length?x.map(p=>'<article class="product" onclick="openProduct('+p.id+')"><span class="tag">'+p.discount+'% OFF</span><img src="'+p.img+'" alt="'+p.name+'" loading="lazy"><div class="stars">★★★★★ <small>(4.8)</small></div><h3>'+p.name+'</h3><div class="old">'+money(p.old)+'</div><div class="price">'+money(p.price)+'</div><div class="pix">à vista no Pix</div><div class="product-hint">Toque para ver opções →</div></article>').join(""):'<div class="empty">Nenhum produto encontrado.<br><button onclick="clearSearch()">Limpar filtros</button></div>'}
function filterCategory(c){state.category=c;state.search="";document.getElementById("searchInput").value="";const names={moda:"Moda"};document.getElementById("sectionTitle").textContent=c==="all"?"Em destaque":(names[c]||"Produtos");document.querySelectorAll(".category-nav button,.chip").forEach(b=>b.classList.remove("active"));renderProducts();document.getElementById("produtos").scrollIntoView({behavior:"smooth"});toggleMenu(false)}
function filterSale(){state.category="all";state.search="";document.getElementById("sectionTitle").textContent="Ofertas";renderProducts();document.getElementById("produtos").scrollIntoView({behavior:"smooth"});toggleMenu(false)}
function searchProducts(){state.search=document.getElementById("searchInput").value.trim();state.category="all";document.getElementById("sectionTitle").textContent=state.search?'Resultados para "'+state.search+'"':"Em destaque";renderProducts();document.getElementById("produtos").scrollIntoView({behavior:"smooth"})}
function focusSearch(){document.querySelector(".desktop-search").scrollIntoView({behavior:"smooth"});setTimeout(()=>document.getElementById("searchInput").focus(),250)}
document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")searchProducts()});
function addCart(id){const item=state.cart.find(x=>x.id===id);if(item)item.qty++;else state.cart.push({id,qty:1});saveCart();showToast("Produto salvo no seu carrinho")}
function saveCart(){localStorage.setItem("ur-cart",JSON.stringify(state.cart));renderCart()}
function renderCart(){const el=document.getElementById("cartItems"),count=state.cart.reduce((n,x)=>n+x.qty,0),total=state.cart.reduce((n,x)=>n+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);document.getElementById("cartCount").textContent=count;document.getElementById("cartTotal").textContent=money(total);el.innerHTML=state.cart.length?state.cart.map(x=>{const p=products.find(p=>p.id===x.id);return '<div class="cart-row"><img src="'+p.img+'"><div><h4>'+p.name+'</h4><div>'+money(p.price)+'</div><div class="qty">Qtd: '+x.qty+' · <button onclick="removeCart('+p.id+')">remover</button></div></div><b>'+money(p.price*x.qty)+'</b></div>'}).join(""):'<div class="empty">Seu carrinho está vazio.</div>'}
function removeCart(id){state.cart=state.cart.filter(x=>x.id!==id);saveCart()}
function toggleCart(){document.getElementById("cart").classList.toggle("open");document.getElementById("overlay").classList.toggle("open")}
function toggleMenu(force){const n=document.getElementById("categoryNav"),b=document.getElementById("menuButton");if(force===false){n.classList.remove("menu-open");b.classList.remove("menu-active");b.textContent="☰";return}const open=n.classList.toggle("menu-open");b.classList.toggle("menu-active",open);b.textContent=open?"×":"☰"}
function compatibleItems(p){return products.filter(x=>x.id!==p.id&&x.isFashion).slice(0,3)}
function combineHtml(p){if(!p.isFashion)return "";const items=compatibleItems(p);return '<section class="combine-box"><div class="eyebrow">UR KINGSLAY</div><h3>✦ Combinar Estilo</h3><p>Veja peças que combinam com esta roupa.</p>'+(!items.length?'<p>Em breve teremos outras peças para completar este look.</p>':'<div class="combine-grid">'+items.map(x=>'<div class="combine-item" onclick="openProduct('+x.id+')"><img src="'+x.img+'" alt="'+x.name+'"><div><b>'+x.name+'</b><span>'+money(x.price)+'</span></div></div>').join("")+'</div>')+'</section>'}
function openProduct(id){const p=products.find(x=>x.id===id);const fav=state.favorites.includes(p.id);document.getElementById("modalContent").innerHTML='<div class="modal-product"><img src="'+p.img+'" alt="'+p.name+'"><div><div class="eyebrow">UR KINGSLAY</div><h2>'+p.name+'</h2><div class="stars">★★★★★ 4.8</div><div class="old">'+money(p.old)+'</div><div class="price">'+money(p.price)+'</div><p class="pix">à vista no Pix</p><p>Veja os detalhes do produto e escolha como deseja continuar.</p><div class="modal-actions"><button class="option-btn primary" onclick="addCart('+p.id+');closeModal()">🛒 Carrinho</button><button class="option-btn favorite '+(fav?"selected":"")+'" onclick="toggleFavorite('+p.id+')">'+(fav?"♥":"♡")+' Favoritar</button><button class="option-btn buy-now" onclick="buyNow('+p.id+')">Comprar agora <span>→</span></button></div>'+combineHtml(p)+'</div></div>';document.getElementById("modal").classList.add("open")}
function closeModal(e){if(!e||e.target.id==="modal")document.getElementById("modal").classList.remove("open")}
function toggleFavorite(id){const i=state.favorites.indexOf(id);if(i>=0)state.favorites.splice(i,1);else state.favorites.push(id);localStorage.setItem("ur-favorites",JSON.stringify(state.favorites));openProduct(id);showToast(i>=0?"Removido dos favoritos":"Adicionado aos favoritos")}
function buyNow(id){const p=products.find(x=>x.id===id);if(!p.buyUrl){showToast("O link da TikTok Shop deste produto ainda não foi cadastrado");return}window.open(p.buyUrl,"_blank","noopener,noreferrer")}
function checkout(){showToast("O carrinho é salvo neste celular. A compra acontece pela TikTok Shop.")}
function subscribe(e){e.preventDefault();showToast("Cadastro realizado!");e.target.reset()}
function showToast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function clearSearch(){state.search="";state.category="all";document.getElementById("searchInput").value="";document.getElementById("sectionTitle").textContent="Em destaque";renderProducts()}
function goHome(){state.category="all";state.search="";document.getElementById("sectionTitle").textContent="Em destaque";document.getElementById("searchInput").value="";window.scrollTo({top:0,behavior:"smooth"});renderProducts()}
renderProducts();renderCart();